FROM php:7-cli

MAINTAINER Konstantin Grachev <preemiere@ya.ru>

RUN docker-php-ext-install mbstring

ADD http://codeception.com/codecept.phar /usr/local/bin/codecept
RUN chmod a+x /usr/local/bin/codecept

ENTRYPOINT ["codecept"]

CMD ["--help"]