FROM php:cli

MAINTAINER Konstantin Grachev <preemiere@ya.ru>

ADD http://codeception.com/codecept.phar /usr/local/bin/codecept
RUN chmod a+x /usr/local/bin/codecept

ENTRYPOINT ["codecept"]

CMD ["--help"]